// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: pb/srv1/srv1.proto

package go_micro_srv_srv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Srv1 service

func NewSrv1Endpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Srv1 service

type Srv1Service interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Srv1_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Srv1_PingPongService, error)
}

type srv1Service struct {
	c    client.Client
	name string
}

func NewSrv1Service(name string, c client.Client) Srv1Service {
	return &srv1Service{
		c:    c,
		name: name,
	}
}

func (c *srv1Service) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Srv1.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srv1Service) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Srv1_StreamService, error) {
	req := c.c.NewRequest(c.name, "Srv1.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &srv1ServiceStream{stream}, nil
}

type Srv1_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type srv1ServiceStream struct {
	stream client.Stream
}

func (x *srv1ServiceStream) Close() error {
	return x.stream.Close()
}

func (x *srv1ServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *srv1ServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *srv1ServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *srv1ServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *srv1Service) PingPong(ctx context.Context, opts ...client.CallOption) (Srv1_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Srv1.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &srv1ServicePingPong{stream}, nil
}

type Srv1_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type srv1ServicePingPong struct {
	stream client.Stream
}

func (x *srv1ServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *srv1ServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *srv1ServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *srv1ServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *srv1ServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *srv1ServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Srv1 service

type Srv1Handler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Srv1_StreamStream) error
	PingPong(context.Context, Srv1_PingPongStream) error
}

func RegisterSrv1Handler(s server.Server, hdlr Srv1Handler, opts ...server.HandlerOption) error {
	type srv1 interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Srv1 struct {
		srv1
	}
	h := &srv1Handler{hdlr}
	return s.Handle(s.NewHandler(&Srv1{h}, opts...))
}

type srv1Handler struct {
	Srv1Handler
}

func (h *srv1Handler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.Srv1Handler.Call(ctx, in, out)
}

func (h *srv1Handler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.Srv1Handler.Stream(ctx, m, &srv1StreamStream{stream})
}

type Srv1_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type srv1StreamStream struct {
	stream server.Stream
}

func (x *srv1StreamStream) Close() error {
	return x.stream.Close()
}

func (x *srv1StreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *srv1StreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *srv1StreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *srv1StreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *srv1Handler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.Srv1Handler.PingPong(ctx, &srv1PingPongStream{stream})
}

type Srv1_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type srv1PingPongStream struct {
	stream server.Stream
}

func (x *srv1PingPongStream) Close() error {
	return x.stream.Close()
}

func (x *srv1PingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *srv1PingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *srv1PingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *srv1PingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *srv1PingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
