basePath: /
definitions:
  db.TBL_USERS:
    properties:
      email:
        type: string
      name:
        example: may
        type: string
      phone:
        type: string
      pwd:
        example: "123"
        type: string
    type: object
  defs.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
host: localhost:4096
info:
  contact:
    email: luxuze@agora.io
    name: API Support
    url: https://github.com/luxuze/Web-Server-Framework-Golang
  license:
    name: DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
    url: https://github.com/luxuze/Web-Server-Framework-Golang/blob/master/LICENSE
  title: Web Server Framework API
  version: 1.0.1
paths:
  /login/register:
    post:
      consumes:
      - application/json
      description: add user
      parameters:
      - description: add user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/db.TBL_USERS'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.TBL_USERS'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/defs.HTTPError'
      summary: user
      tags:
      - user
  /wx:
    get:
      consumes:
      - application/json
      description: Request WX get resp
      parameters:
      - default: "123"
        description: Request WX
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Wx
      tags:
      - WX
swagger: "2.0"
