// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: pkg/proto/svc2/svc2.proto

package svc2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Svc2 service

func NewSvc2Endpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Svc2 service

type Svc2Service interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Svc2_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Svc2_PingPongService, error)
}

type svc2Service struct {
	c    client.Client
	name string
}

func NewSvc2Service(name string, c client.Client) Svc2Service {
	return &svc2Service{
		c:    c,
		name: name,
	}
}

func (c *svc2Service) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Svc2.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *svc2Service) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Svc2_StreamService, error) {
	req := c.c.NewRequest(c.name, "Svc2.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &svc2ServiceStream{stream}, nil
}

type Svc2_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type svc2ServiceStream struct {
	stream client.Stream
}

func (x *svc2ServiceStream) Close() error {
	return x.stream.Close()
}

func (x *svc2ServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *svc2ServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *svc2ServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *svc2ServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *svc2Service) PingPong(ctx context.Context, opts ...client.CallOption) (Svc2_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Svc2.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &svc2ServicePingPong{stream}, nil
}

type Svc2_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type svc2ServicePingPong struct {
	stream client.Stream
}

func (x *svc2ServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *svc2ServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *svc2ServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *svc2ServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *svc2ServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *svc2ServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Svc2 service

type Svc2Handler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Svc2_StreamStream) error
	PingPong(context.Context, Svc2_PingPongStream) error
}

func RegisterSvc2Handler(s server.Server, hdlr Svc2Handler, opts ...server.HandlerOption) error {
	type svc2 interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Svc2 struct {
		svc2
	}
	h := &svc2Handler{hdlr}
	return s.Handle(s.NewHandler(&Svc2{h}, opts...))
}

type svc2Handler struct {
	Svc2Handler
}

func (h *svc2Handler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.Svc2Handler.Call(ctx, in, out)
}

func (h *svc2Handler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.Svc2Handler.Stream(ctx, m, &svc2StreamStream{stream})
}

type Svc2_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type svc2StreamStream struct {
	stream server.Stream
}

func (x *svc2StreamStream) Close() error {
	return x.stream.Close()
}

func (x *svc2StreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *svc2StreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *svc2StreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *svc2StreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *svc2Handler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.Svc2Handler.PingPong(ctx, &svc2PingPongStream{stream})
}

type Svc2_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type svc2PingPongStream struct {
	stream server.Stream
}

func (x *svc2PingPongStream) Close() error {
	return x.stream.Close()
}

func (x *svc2PingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *svc2PingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *svc2PingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *svc2PingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *svc2PingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
