// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.1
// source: pkg/proto/svc1/svc1.proto

package svc1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CallSvc2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CallSvc2Request) Reset() {
	*x = CallSvc2Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_svc1_svc1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallSvc2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallSvc2Request) ProtoMessage() {}

func (x *CallSvc2Request) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_svc1_svc1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallSvc2Request.ProtoReflect.Descriptor instead.
func (*CallSvc2Request) Descriptor() ([]byte, []int) {
	return file_pkg_proto_svc1_svc1_proto_rawDescGZIP(), []int{0}
}

func (x *CallSvc2Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CallSvc2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CallSvc2Response) Reset() {
	*x = CallSvc2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_svc1_svc1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallSvc2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallSvc2Response) ProtoMessage() {}

func (x *CallSvc2Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_svc1_svc1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallSvc2Response.ProtoReflect.Descriptor instead.
func (*CallSvc2Response) Descriptor() ([]byte, []int) {
	return file_pkg_proto_svc1_svc1_proto_rawDescGZIP(), []int{1}
}

func (x *CallSvc2Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pkg_proto_svc1_svc1_proto protoreflect.FileDescriptor

var file_pkg_proto_svc1_svc1_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x76, 0x63, 0x31,
	0x2f, 0x73, 0x76, 0x63, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x67, 0x6f, 0x2e,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x73, 0x76,
	0x63, 0x31, 0x22, 0x25, 0x0a, 0x0f, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x76, 0x63, 0x32, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x24, 0x0a, 0x10, 0x43, 0x61, 0x6c,
	0x6c, 0x53, 0x76, 0x63, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32,
	0x65, 0x0a, 0x04, 0x53, 0x76, 0x63, 0x31, 0x12, 0x5d, 0x0a, 0x08, 0x43, 0x61, 0x6c, 0x6c, 0x53,
	0x76, 0x63, 0x32, 0x12, 0x26, 0x2e, 0x67, 0x6f, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x73, 0x76, 0x63, 0x31, 0x2e, 0x43, 0x61, 0x6c, 0x6c,
	0x53, 0x76, 0x63, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x67, 0x6f,
	0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x73,
	0x76, 0x63, 0x31, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x76, 0x63, 0x32, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x76, 0x63, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_svc1_svc1_proto_rawDescOnce sync.Once
	file_pkg_proto_svc1_svc1_proto_rawDescData = file_pkg_proto_svc1_svc1_proto_rawDesc
)

func file_pkg_proto_svc1_svc1_proto_rawDescGZIP() []byte {
	file_pkg_proto_svc1_svc1_proto_rawDescOnce.Do(func() {
		file_pkg_proto_svc1_svc1_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_svc1_svc1_proto_rawDescData)
	})
	return file_pkg_proto_svc1_svc1_proto_rawDescData
}

var file_pkg_proto_svc1_svc1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_svc1_svc1_proto_goTypes = []interface{}{
	(*CallSvc2Request)(nil),  // 0: go.micro.service.svc1.CallSvc2Request
	(*CallSvc2Response)(nil), // 1: go.micro.service.svc1.CallSvc2Response
}
var file_pkg_proto_svc1_svc1_proto_depIdxs = []int32{
	0, // 0: go.micro.service.svc1.Svc1.CallSvc2:input_type -> go.micro.service.svc1.CallSvc2Request
	1, // 1: go.micro.service.svc1.Svc1.CallSvc2:output_type -> go.micro.service.svc1.CallSvc2Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_svc1_svc1_proto_init() }
func file_pkg_proto_svc1_svc1_proto_init() {
	if File_pkg_proto_svc1_svc1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_svc1_svc1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallSvc2Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_svc1_svc1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallSvc2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_svc1_svc1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_svc1_svc1_proto_goTypes,
		DependencyIndexes: file_pkg_proto_svc1_svc1_proto_depIdxs,
		MessageInfos:      file_pkg_proto_svc1_svc1_proto_msgTypes,
	}.Build()
	File_pkg_proto_svc1_svc1_proto = out.File
	file_pkg_proto_svc1_svc1_proto_rawDesc = nil
	file_pkg_proto_svc1_svc1_proto_goTypes = nil
	file_pkg_proto_svc1_svc1_proto_depIdxs = nil
}
